# Generated by Django 3.0.3 on 2020-03-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MajorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SciorArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SciorArt', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('testnum', models.CharField(max_length=14)),
                ('score', models.PositiveSmallIntegerField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('tele', models.CharField(max_length=20)),
                ('high_school', models.CharField(max_length=30)),
                ('application_rank', models.PositiveSmallIntegerField()),
                ('stuffid', models.PositiveIntegerField(default=0)),
                ('place', models.CharField(default='NULL', max_length=30)),
                ('tip', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.MajorInfo')),
                ('sciorart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.SciorArt')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='RankPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('highrank', models.PositiveSmallIntegerField()),
                ('lowrank', models.PositiveSmallIntegerField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.ProvinceInfo')),
            ],
        ),
    ]
