# Generated by Django 3.0.3 on 2020-03-23 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200323_1520'),
        ('information', '0002_auto_20200316_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuinfo',
            name='major',
        ),
        migrations.RemoveField(
            model_name='stuinfo',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='major1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major1', to='information.MajorInfo'),
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='major2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major2', to='information.MajorInfo'),
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='major3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major3', to='information.MajorInfo'),
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Province'),
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rankpredict',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Province'),
        ),
        migrations.DeleteModel(
            name='ProvinceInfo',
        ),
    ]
