# Generated by Django 3.0.3 on 2020-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20200325_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorinfo',
            name='major_name',
            field=models.CharField(max_length=30),
        ),
    ]
