# Generated by Django 3.0.3 on 2020-04-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20200407_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultmaterial',
            name='file',
            field=models.FileField(default='image/default.pdf', upload_to='material'),
        ),
    ]
