# Generated by Django 3.0.3 on 2020-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20200408_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultmaterial',
            name='file',
        ),
        migrations.AddField(
            model_name='consultmaterial',
            name='file_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
