# Generated by Django 3.0.3 on 2020-03-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0007_auto_20200326_2331'),
        ('users', '0003_auto_20200323_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_major', to='information.MajorInfo')),
                ('province', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_province', to='users.Province')),
            ],
        ),
    ]
