# Generated by Django 3.0.3 on 2020-03-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200323_1520'),
        ('adminsite', '0002_auto_20200327_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyinfo',
            name='province',
        ),
        migrations.AddField(
            model_name='historyinfo',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_province', to='users.Province'),
            preserve_default=False,
        ),
    ]
