# Generated by Django 3.0.3 on 2020-03-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_auto_20200326_2331'),
        ('users', '0003_auto_20200323_1520'),
        ('adminsite', '0003_auto_20200327_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorderlinePredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowscore', models.IntegerField(blank=True, null=True)),
                ('highscore', models.IntegerField(blank=True, null=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_major', to='information.MajorInfo')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_province', to='users.Province')),
            ],
        ),
    ]
