# Generated by Django 3.0.3 on 2020-03-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuinfo',
            old_name='stuffid',
            new_name='staff_id',
        ),
    ]
