# Generated by Django 3.0.3 on 2020-03-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20200323_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorinfo',
            name='major_name',
            field=models.CharField(max_length=15),
        ),
    ]
