# Generated by Django 3.0.3 on 2020-03-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20200323_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankpredict',
            name='sciorart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='information.SciorArt'),
        ),
        migrations.AlterField(
            model_name='rankpredict',
            name='highrank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankpredict',
            name='lowrank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
